export const topText1 = "Hi, I'm Jose"
export const topText2 = "Welcome to my portofolio"
// export const bottomText1 = "「いらっしゃい」"
export const bottomText1 = "いらっしゃい"
export const bottomText2 = "Fullstack Developer"